### ISSUE TITLE
Add more stations

### ISSUE THREAD

**Issue by equivalentideas** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#18]
The NSW gov publishes hourly averages here http://www.environment.nsw.gov.au/AQMS/search.htm

You can get their data submission form to send through a strangely formatted csv file to parse.

**Comment by henare** [comment]
Our current scraper is saving the 10-minutely data of air quality monitors where that raw data is averaged and no longer available after it's initially published. Since the OEH site makes available all of the raw data that's presented on their site as a download there's no as much value in scraping it.

I'm going to boldly close this as I don't think we have any immediate plans to do this. I don't think there's no value in doing it, as it backs up this data and can make it available in a more easy to use form, but I think it would be very low on our priority list.

If we do decide we want this, either now or at some stage in the future, I think we should open a new issue specifically about _this_ data (as opposed to the more generic, "other data sources").
